[package]
name = "recaptcha_invisible_bypass"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
form_urlencoded = "1.2.1"
percent-encoding = "2.3.1"
reqwest = "0.12.8"
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros"] }
